# Generated by Django 5.1.5 on 2025-01-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_pda', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('indicador', models.TextField()),
                ('formula_calculo', models.TextField()),
                ('frecuencia_reporte', models.CharField(choices=[('anual', 'Anual'), ('unica', 'Única'), ('cada_5_anos', 'Cada 5 años')], max_length=50)),
                ('tipo_medida', models.CharField(choices=[('regulatoria', 'Regulatoria'), ('no_regulatoria', 'No Regulatoria')], max_length=50)),
                ('plazo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedioVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('informe_anual', 'Informe Anual'), ('documento_excel', 'Documento Excel'), ('fotografia', 'Fotografía'), ('reporte', 'Reporte'), ('resolucion', 'Resolución'), ('registro_interno', 'Registro Interno'), ('oficio', 'Oficio')], max_length=50)),
                ('entidad_a_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medios_verificacion', to='app_reporte.entidad')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_verificacion', to='app_reporte.medida')),
            ],
        ),
        migrations.AddField(
            model_name='medida',
            name='organismos',
            field=models.ManyToManyField(related_name='medidas', to='app_reporte.organismoresponsable'),
        ),
        migrations.CreateModel(
            name='PlanPPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mes_reporte', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('comunas', models.ManyToManyField(related_name='planes', to='app_reporte.comuna')),
            ],
        ),
    ]
