# Generated by Django 5.1.5 on 2025-04-05 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0002_ciudad_region_comuna_ciudad_ciudad_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='app_reporte.ciudad'),
        ),
        migrations.AlterField(
            model_name='planppda',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre único del Plan, identificando claramente las comunas que corresponden.', max_length=255),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField()),
                ('descripcion', models.TextField()),
                ('archivo_url', models.URLField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reporte.medida')),
                ('medio_verificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_reporte.medioverificacion')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reporte.organismoresponsable')),
            ],
        ),
    ]
