# Generated by Django 5.1.5 on 2025-04-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0002_ciudad_region_comuna_ciudad_ciudad_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='app_reporte.ciudad'),
        ),
        migrations.AlterField(
            model_name='planppda',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre único del Plan, identificando claramente las comunas que corresponden.', max_length=255),
        ),
        migrations.CreateModel(
            name='ReporteAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('plan_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_anuales', to='app_reporte.planppda')),
            ],
        ),
    ]
