# Generated by Django 5.1.5 on 2025-04-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0003_alter_comuna_ciudad_alter_planppda_nombre_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planppda',
            name='mes_reporte',
            field=models.IntegerField(help_text='Ingrese un valor'),
        ),
    ]
