# Generated by Django 5.1.5 on 2025-04-14 03:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0006_reporte_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('actualizado_por', models.CharField(max_length=100)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reporte.reporte')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Estado',
                'verbose_name_plural': 'Historiales de Cambios de Estado',
            },
        ),
    ]
