# Generated by Django 5.1.5 on 2025-04-27 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0006_reporte_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=255)),
                ('responsable_plan', models.CharField(max_length=255)),
                ('fecha_plan', models.DateField()),
                ('estado_plan', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=255)),
                ('reporte_entregado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoProbatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('url_documento', models.URLField(max_length=500)),
                ('reporte_anual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_probatorios', to='app_reporte.reporteanual')),
            ],
        ),
    ]
