# Generated by Django 5.1.5 on 2025-04-28 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0007_reporteanual_elementoprobatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoprobatorio',
            name='medio_de_verificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporteanual',
            name='ciudad',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteanual',
            name='comuna',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteanual',
            name='medida',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteanual',
            name='region',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
