# Generated by Django 5.1.5 on 2025-04-14 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reporte', '0007_historialestadoreporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialestadoreporte',
            name='fecha_cambio',
        ),
        migrations.AddField(
            model_name='historialestadoreporte',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
