name: CI SMA
on:
  pull_request:
    branches: [main]
  push:
    branches: [dev, inclusion_ci]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ejecutar pruebas
      run: |
        python manage.py test